#!/bin/bash

set -e

source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

header "Clojure tests"
clojure -X:test

header "ClojureScript tests"
npm install --silent
npx shadow-cljs compile test
node target/test.js

header "Babashka tests"
bb test/bb_test_runner.clj

ok "All tests passed"
